import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  websiteSidebar: [
    {type: 'autogenerated', dirName: 'website'},
  ],
  insuranceSidebar: [
    {type: 'autogenerated', dirName: 'insurance'},
  ],
};

export default sidebars;